# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camerapage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
import numpy
import time


class Ui_ARWindow(object):
    def setupUi(self, ARWindow):
        ARWindow.setObjectName("ARWindow")
        ARWindow.resize(1920, 1080)

        self.centralwidget = QtWidgets.QWidget(ARWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Label = QtWidgets.QLabel(self.centralwidget)
        self.Label.setGeometry(QtCore.QRect(10, 10, 1881, 971))
        self.Label.setFrameShape(QtWidgets.QFrame.Box)
        self.Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Label.setLineWidth(0)
        self.Label.setObjectName("Label")

        self.nio = QtWidgets.QPushButton(self.centralwidget)
        self.nio.setGeometry(QtCore.QRect(1760, 1010, 75, 24))
        self.nio.setObjectName("nio")

        self.Worker1 = Worker1()
        self.Worker1.start()
        self.Worker1.ImageUpdate.connect(self.ImageUpdateSlot)

        self.io = QtWidgets.QPushButton(self.centralwidget)
        self.io.setGeometry(QtCore.QRect(1840, 1010, 75, 24))
        self.io.setObjectName("io")
        ARWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(ARWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        ARWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(ARWindow)
        self.statusbar.setObjectName("statusbar")
        ARWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ARWindow)
        QtCore.QMetaObject.connectSlotsByName(ARWindow)

    def retranslateUi(self, ARWindow):
        _translate = QtCore.QCoreApplication.translate
        ARWindow.setWindowTitle(_translate("ARWindow", "MainWindow"))
        self.nio.setText(_translate("ARWindow", "n.i.O."))
        self.io.setText(_translate("ARWindow", "i.O."))

    def ImageUpdateSlot(self, Image):
        self.Label.setPixmap(QtGui.QPixmap.fromImage(Image))

class Worker1(QtCore.QThread):
    ImageUpdate = QtCore.pyqtSignal(QtGui.QImage)
    def run(self):
        self.ThreadActive = True
        Capture = cv2.VideoCapture(0)
        Capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
        Capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)
        while self.ThreadActive:
            start_time = time.time()
            ret, frame = Capture.read()
            if ret:
                Image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                FlippedImage = cv2.flip(Image, 1)
                FlippedImage = cv2.line(FlippedImage, (0,0), x, 0, 5)
                if x[1] < 720:
                    x[0] = x[0] + 20
                    x[1] = x[1] + 20
                else:
                    x[0] = 0
                    x[1] = 0
                ConvertToQtFormat = QtGui.QImage(FlippedImage.data, FlippedImage.shape[1], FlippedImage.shape[0], QtGui.
                                                 QImage.Format_RGB888)
                Pic = ConvertToQtFormat.scaled(1600, 900, QtCore.Qt.KeepAspectRatio)
                self.ImageUpdate.emit(Pic)
                print('FPS {:.1f}'.format(1 / (time.time() - start_time)))


x = [0, 0]

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ARWindow = QtWidgets.QMainWindow()
    ui = Ui_ARWindow()
    ui.setupUi(ARWindow)
    ARWindow.show()
    sys.exit(app.exec_())
