# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from mappage import Ui_mappage
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets
import io
import folium
import cv2
import numpy
import time


class Ui_FrontWindow(QtWidgets.QWidget):
    def setupUi(self, Main):
        Main.setObjectName("AR-Machine1.o")
        Main.resize(1920, 1080)

        self.QtStack = QtWidgets.QStackedLayout()

        self.stack1 = QtWidgets.QWidget()
        self.stack2 = QtWidgets.QWidget()
        #self.stack3 = QtWidgets.QWidget()

        self.Window1UI()
        self.Window2UI()
        #self.Window3UI()

        self.QtStack.addWidget(self.stack1)
        self.QtStack.addWidget(self.stack2)
        #self.QtStack.addWidget(self.stack3)

    def Window1UI(self):
        self.stack1.setObjectName("FrontWindow")
        self.stack1.resize(155, 180)
        #self.centralwidget = QtWidgets.QWidget(FrontWindow)
        #self.centralwidget.setObjectName("centralwidget")
        self.Scenario1 = QtWidgets.QPushButton(self.stack1)
        self.Scenario1.setGeometry(QtCore.QRect(40, 10, 75, 30))
        self.Scenario1.setObjectName("Scenario1")

        # def action(self):
        #     self.mappage()
        #
        # self.Scenario1.clicked.connect(lambda: action(self))

        # self.Scenario2 = QtWidgets.QPushButton(self.centralwidget)
        # self.Scenario2.setGeometry(QtCore.QRect(40, 40, 75, 30))
        # self.Scenario2.setObjectName("Scenario2")
        # self.Scenario3 = QtWidgets.QPushButton(self.centralwidget)
        # self.Scenario3.setGeometry(QtCore.QRect(40, 70, 75, 30))
        # self.Scenario3.setObjectName("Scenario3")
        # self.Scenario4 = QtWidgets.QPushButton(self.centralwidget)
        # self.Scenario4.setGeometry(QtCore.QRect(40, 100, 75, 30))
        # self.Scenario4.setObjectName("Scenario4")
        # self.Scenario5 = QtWidgets.QPushButton(self.centralwidget)
        # self.Scenario5.setGeometry(QtCore.QRect(40, 130, 75, 30))
        # self.Scenario5.setObjectName("Scenario5")
        # FrontWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(FrontWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 155, 21))
        # self.menubar.setObjectName("menubar")
        # FrontWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(FrontWindow)
        # self.statusbar.setObjectName("statusbar")
        # FrontWindow.setStatusBar(self.statusbar)
        #
        # self.retranslateUi1(FrontWindow)
        # QtCore.QMetaObject.connectSlotsByName(FrontWindow)

    def retranslateUi1(self, FrontWindow):
        _translate = QtCore.QCoreApplication.translate
        FrontWindow.setWindowTitle(_translate("FrontWindow", "MainWindow"))
        self.Scenario1.setText(_translate("FrontWindow", "Scenario 1"))
        self.Scenario2.setText(_translate("FrontWindow", "Scenario 2"))
        self.Scenario3.setText(_translate("FrontWindow", "Scenario 3"))
        self.Scenario4.setText(_translate("FrontWindow", "Scenario 4"))
        self.Scenario5.setText(_translate("FrontWindow", "Scenario 5"))

    def Window2UI(self):
        self.Label = QtWidgets.QLabel(self.stack2)
        self.Label.setGeometry(QtCore.QRect(10, 10, 1881, 971))
        self.Label.setFrameShape(QtWidgets.QFrame.Box)
        self.Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Label.setLineWidth(0)
        self.Label.setObjectName("Label")

        self.nio = QtWidgets.QPushButton(self.stack2)
        self.nio.setGeometry(QtCore.QRect(1760, 1010, 75, 24))
        self.nio.setObjectName("nio")

        self.Worker1 = Worker1()
        self.Worker1.start()
        self.Worker1.ImageUpdate.connect(self.ImageUpdateSlot)

        self.io = QtWidgets.QPushButton(self.stack2)
        self.io.setGeometry(QtCore.QRect(1840, 1010, 75, 24))
        self.io.setObjectName("io")

        # self.menubar = QtWidgets.QMenuBar(ARWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        # self.menubar.setObjectName("menubar")
        # ARWindow.setMenuBar(self.menubar)
        #
        # self.statusbar = QtWidgets.QStatusBar(ARWindow)
        # self.statusbar.setObjectName("statusbar")
        # ARWindow.setStatusBar(self.statusbar)
        #
        # self.retranslateUi(ARWindow)
        # QtCore.QMetaObject.connectSlotsByName(ARWindow)

    def retranslateUi(self, ARWindow):
        _translate = QtCore.QCoreApplication.translate
        ARWindow.setWindowTitle(_translate("ARWindow", "MainWindow"))
        self.nio.setText(_translate("ARWindow", "n.i.O."))
        self.io.setText(_translate("ARWindow", "i.O."))

    def ImageUpdateSlot(self, Image):
        self.Label.setPixmap(QtGui.QPixmap.fromImage(Image))

class Worker1(QtCore.QThread):
    ImageUpdate = QtCore.pyqtSignal(QtGui.QImage)
    def run(self):
        self.ThreadActive = True
        Capture = cv2.VideoCapture(0)
        Capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
        Capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)
        x = [0, 0]
        while self.ThreadActive:
            start_time = time.time()
            ret, frame = Capture.read()
            if ret:
                Image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                FlippedImage = cv2.flip(Image, 1)
                FlippedImage = cv2.line(FlippedImage, (0,0), x, 0, 5)

                if x[1] < 720:
                    x[0] = x[0] + 20
                    x[1] = x[1] + 20
                else:
                    x[0] = 0
                    x[1] = 0
                ConvertToQtFormat = QtGui.QImage(FlippedImage.data, FlippedImage.shape[1], FlippedImage.shape[0], QtGui.
                                                 QImage.Format_RGB888)
                Pic = ConvertToQtFormat.scaled(1600, 900, QtCore.Qt.KeepAspectRatio)
                self.ImageUpdate.emit(Pic)
                print('FPS {:.1f}'.format(1 / (time.time() - start_time)))



