# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import io
from mappage import Ui_mappage
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrontWindow(object):
    def mappage(self):
        import sys
        #app = QtWidgets.QApplication(sys.argv)
        self.maps_1 = QtWidgets.QMainWindow()
        ui = Ui_mappage()
        ui.setupUi(self.maps_1)
        self.maps_1.show()
        #FrontWindow.close()
    # #     #sys.exit(app.exec_())

    def setupUi(self, FrontWindow):
        FrontWindow.setObjectName("FrontWindow")
        FrontWindow.resize(155, 180)
        self.centralwidget = QtWidgets.QWidget(FrontWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layout_for_windows = QtWidgets.QStackedLayout()

        self.Scenario1 = QtWidgets.QPushButton(self.centralwidget)
        self.Scenario1.setGeometry(QtCore.QRect(40, 10, 75, 30))
        self.Scenario1.setObjectName("Scenario1")

        self.Scenario1.clicked.connect(self.action)

        self.Scenario2 = QtWidgets.QPushButton(self.centralwidget)
        self.Scenario2.setGeometry(QtCore.QRect(40, 40, 75, 30))
        self.Scenario2.setObjectName("Scenario2")
        self.Scenario3 = QtWidgets.QPushButton(self.centralwidget)
        self.Scenario3.setGeometry(QtCore.QRect(40, 70, 75, 30))
        self.Scenario3.setObjectName("Scenario3")
        self.Scenario4 = QtWidgets.QPushButton(self.centralwidget)
        self.Scenario4.setGeometry(QtCore.QRect(40, 100, 75, 30))
        self.Scenario4.setObjectName("Scenario4")
        self.Scenario5 = QtWidgets.QPushButton(self.centralwidget)
        self.Scenario5.setGeometry(QtCore.QRect(40, 130, 75, 30))
        self.Scenario5.setObjectName("Scenario5")
        FrontWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FrontWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 155, 21))
        self.menubar.setObjectName("menubar")
        FrontWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FrontWindow)
        self.statusbar.setObjectName("statusbar")
        FrontWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FrontWindow)
        QtCore.QMetaObject.connectSlotsByName(FrontWindow)



    def action(self):
        self.mappage()

    def retranslateUi(self, FrontWindow):
        _translate = QtCore.QCoreApplication.translate
        FrontWindow.setWindowTitle(_translate("FrontWindow", "MainWindow"))
        self.Scenario1.setText(_translate("FrontWindow", "Scenario 1"))
        self.Scenario2.setText(_translate("FrontWindow", "Scenario 2"))
        self.Scenario3.setText(_translate("FrontWindow", "Scenario 3"))
        self.Scenario4.setText(_translate("FrontWindow", "Scenario 4"))
        self.Scenario5.setText(_translate("FrontWindow", "Scenario 5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrontWindow = QtWidgets.QMainWindow()
    ui = Ui_FrontWindow()
    ui.setupUi(FrontWindow)
    FrontWindow.show()
    sys.exit(app.exec_())
