# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from mappage import Ui_mappage
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWebEngineWidgets
import io
import folium


class Ui_FrontWindow(QtWidgets.QWidget):
    def setupUi(self, Main):
        Main.setObjectName("AR-Machine1.o")
        Main.resize(1920, 1080)

        self.QtStack = QtWidgets.QStackedLayout()

        self.stack1 = QtWidgets.QWidget()
        self.stack2 = QtWidgets.QWidget()
        #self.stack3 = QtWidgets.QWidget()

        self.Window1UI()
        self.Window2UI()
        #self.Window3UI()

        self.QtStack.addWidget(self.stack1)
        self.QtStack.addWidget(self.stack2)
        #self.QtStack.addWidget(self.stack3)

    def Window1UI(self):
        self.stack1.setObjectName("FrontWindow")
        self.stack1.resize(155, 180)
        #self.centralwidget = QtWidgets.QWidget(FrontWindow)
        #self.centralwidget.setObjectName("centralwidget")
        self.Scenario1 = QtWidgets.QPushButton(self.stack1)
        self.Scenario1.setGeometry(QtCore.QRect(40, 10, 75, 30))
        self.Scenario1.setObjectName("Scenario1")

        # def action(self):
        #     self.mappage()
        #
        # self.Scenario1.clicked.connect(lambda: action(self))

        # self.Scenario2 = QtWidgets.QPushButton(self.centralwidget)
        # self.Scenario2.setGeometry(QtCore.QRect(40, 40, 75, 30))
        # self.Scenario2.setObjectName("Scenario2")
        # self.Scenario3 = QtWidgets.QPushButton(self.centralwidget)
        # self.Scenario3.setGeometry(QtCore.QRect(40, 70, 75, 30))
        # self.Scenario3.setObjectName("Scenario3")
        # self.Scenario4 = QtWidgets.QPushButton(self.centralwidget)
        # self.Scenario4.setGeometry(QtCore.QRect(40, 100, 75, 30))
        # self.Scenario4.setObjectName("Scenario4")
        # self.Scenario5 = QtWidgets.QPushButton(self.centralwidget)
        # self.Scenario5.setGeometry(QtCore.QRect(40, 130, 75, 30))
        # self.Scenario5.setObjectName("Scenario5")
        # FrontWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(FrontWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 155, 21))
        # self.menubar.setObjectName("menubar")
        # FrontWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(FrontWindow)
        # self.statusbar.setObjectName("statusbar")
        # FrontWindow.setStatusBar(self.statusbar)
        #
        # self.retranslateUi1(FrontWindow)
        # QtCore.QMetaObject.connectSlotsByName(FrontWindow)

    def retranslateUi1(self, FrontWindow):
        _translate = QtCore.QCoreApplication.translate
        FrontWindow.setWindowTitle(_translate("FrontWindow", "MainWindow"))
        self.Scenario1.setText(_translate("FrontWindow", "Scenario 1"))
        self.Scenario2.setText(_translate("FrontWindow", "Scenario 2"))
        self.Scenario3.setText(_translate("FrontWindow", "Scenario 3"))
        self.Scenario4.setText(_translate("FrontWindow", "Scenario 4"))
        self.Scenario5.setText(_translate("FrontWindow", "Scenario 5"))

    def Window2UI(self):
        #self.centralwidget = QtWidgets.QWidget(mappage)
        #self.centralwidget.setObjectName("centralwidget")

        self.maps = QtWebEngineWidgets.QWebEngineView(self.stack2)
        self.maps.setGeometry(QtCore.QRect(10, 20, 1181, 1001))
        self.maps.setObjectName("maps")

        coordinate1 = (49.85535748057516, 7.60608913278368)
        m = folium.Map(
            tiles='OpenStreetMap',
            zoom_start=18,
            location=coordinate1
        )
        startpos = [49.85535748057516, 7.60608913278368]

        folium.Marker(startpos, popup='Start Position').add_to(m)

        folium.Circle(
            radius=100,
            location=[49.85535748057516, 7.60608913278368],
            color="crimson",
            fill=True,
        ).add_to(m)

        # save map data to data object
        data = io.BytesIO()
        m.save(data, close_file=False)
        self.maps.setHtml(data.getvalue().decode())

        self.startlat = QtWidgets.QLabel(self.stack2)
        self.startlat.setGeometry(QtCore.QRect(1400, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startlat.setFont(font)
        self.startlat.setMouseTracking(False)
        self.startlat.setObjectName("startlat")

        self.startlong = QtWidgets.QLabel(self.stack2)
        self.startlong.setGeometry(QtCore.QRect(1400, 120, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startlong.setFont(font)
        self.startlong.setObjectName("startlong")

        self.endlat = QtWidgets.QLabel(self.stack2)
        self.endlat.setGeometry(QtCore.QRect(1400, 290, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endlat.setFont(font)
        self.endlat.setMouseTracking(False)
        self.endlat.setObjectName("endlat")

        self.endlong = QtWidgets.QLabel(self.stack2)
        self.endlong.setGeometry(QtCore.QRect(1400, 330, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endlong.setFont(font)
        self.endlong.setMouseTracking(False)
        self.endlong.setObjectName("endlong")

        self.startlat_2 = QtWidgets.QLabel(self.stack2)
        self.startlat_2.setGeometry(QtCore.QRect(1590, 80, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startlat_2.setFont(font)
        self.startlat_2.setMouseTracking(False)
        self.startlat_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.startlat_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.startlat_2.setObjectName("startlat_2")

        self.startlong_2 = QtWidgets.QLabel(self.stack2)
        self.startlong_2.setGeometry(QtCore.QRect(1590, 120, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startlong_2.setFont(font)
        self.startlong_2.setMouseTracking(False)
        self.startlong_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.startlong_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.startlong_2.setLineWidth(1)
        self.startlong_2.setTextFormat(QtCore.Qt.AutoText)
        self.startlong_2.setWordWrap(False)
        self.startlong_2.setObjectName("startlong_2")

        self.endlat_2 = QtWidgets.QLabel(self.stack2)
        self.endlat_2.setGeometry(QtCore.QRect(1590, 290, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endlat_2.setFont(font)
        self.endlat_2.setMouseTracking(False)
        self.endlat_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.endlat_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.endlat_2.setObjectName("endlat_2")

        self.endlong_2 = QtWidgets.QLabel(self.stack2)
        self.endlong_2.setGeometry(QtCore.QRect(1590, 330, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endlong_2.setFont(font)
        self.endlong_2.setMouseTracking(False)
        self.endlong_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.endlong_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.endlong_2.setObjectName("endlong_2")

        self.uhrzeit = QtWidgets.QLabel(self.stack2)
        self.uhrzeit.setGeometry(QtCore.QRect(1630, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.uhrzeit.setFont(font)
        self.uhrzeit.setAlignment(QtCore.Qt.AlignCenter)
        self.uhrzeit.setObjectName("uhrzeit")
        #Main.self.stack2(self.stack2)

        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.showTime)
        self.timer.start(1000)

        self.startbutton = QtWidgets.QPushButton(self.stack2)
        self.startbutton.setGeometry(QtCore.QRect(1690, 160, 171, 28))
        self.startbutton.setObjectName("startbutton")

        self.endbutton = QtWidgets.QPushButton(self.stack2)
        self.endbutton.setGeometry(QtCore.QRect(1690, 370, 171, 28))
        self.endbutton.setObjectName("endbutton")

        self.distance = QtWidgets.QLabel(self.stack2)
        self.distance.setGeometry(QtCore.QRect(1280, 480, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.distance.setFont(font)
        self.distance.setMouseTracking(False)
        self.distance.setObjectName("distance")

        self.distance_2 = QtWidgets.QLabel(self.stack2)
        self.distance_2.setGeometry(QtCore.QRect(1590, 480, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.distance_2.setFont(font)
        self.distance_2.setMouseTracking(False)
        self.distance_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.distance_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.distance_2.setObjectName("distance_2")
        self.heading = QtWidgets.QLabel(self.stack2)
        self.heading.setGeometry(QtCore.QRect(1370, 520, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.heading.setFont(font)
        self.heading.setMouseTracking(False)
        self.heading.setObjectName("heading")

        self.heading_2 = QtWidgets.QLabel(self.stack2)
        self.heading_2.setGeometry(QtCore.QRect(1590, 520, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.heading_2.setFont(font)
        self.heading_2.setMouseTracking(False)
        self.heading_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.heading_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.heading_2.setObjectName("heading_2")

        self.maps_coor_table = QtWidgets.QTableWidget(self.stack2)
        self.maps_coor_table.setGeometry(QtCore.QRect(1280, 590, 581, 321))
        self.maps_coor_table.setObjectName("maps_coor_table")
        self.maps_coor_table.setColumnCount(0)
        self.maps_coor_table.setRowCount(0)

        self.next_maps = QtWidgets.QPushButton(self.stack2)
        self.next_maps.setGeometry(QtCore.QRect(1690, 990, 171, 28))
        self.next_maps.setObjectName("next_maps")
        #Main.setCentralWidget(self.stack2)

        # def action(self):
        #     self.instructionpage()

        #self.next_maps.clicked.connect(lambda: action(self))

        #self.menubar = QtWidgets.QMenuBar(Main)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        #self.menubar.setObjectName("menubar")
        #Main.setMenuBar(self.menubar)

        #self.statusbar = QtWidgets.QStatusBar(Main)
        #self.statusbar.setObjectName("statusbar")
        #Main.setStatusBar(self.statusbar)

        #self.retranslateUi2(Main)
        #QtCore.QMetaObject.connectSlotsByName(Main)

    def showTime(self):
        current_time = QtCore.QTime.currentTime()
        # converting QTime object to string
        label_time = current_time.toString('hh:mm:ss')
        # showing it to the label
        self.uhrzeit.setText(label_time)

    def retranslateUi2(self, mappage):
        _translate = QtCore.QCoreApplication.translate
        mappage.setWindowTitle(_translate("mappage", "MainWindow"))
        self.startlat.setText(_translate("mappage", "Start Latitude"))
        self.startlong.setText(_translate("mappage", "Start Longitude"))
        self.endlat.setText(_translate("mappage", "End Latitude"))
        self.endlong.setText(_translate("mappage", "End Longitude"))
        self.startlat_2.setText(_translate("mappage", "Start Latitude"))
        self.startlong_2.setText(_translate("mappage", "Start Longitude"))
        self.endlat_2.setText(_translate("mappage", "End Latitude"))
        self.endlong_2.setText(_translate("mappage", "End Latitude"))
        self.startbutton.setText(_translate("mappage", "Set as Startposition"))
        self.endbutton.setText(_translate("mappage", "Set as Endposition"))
        self.distance.setText(_translate("mappage", "Distance from start to end"))
        self.distance_2.setText(_translate("mappage", "Distance"))
        self.heading.setText(_translate("mappage", "Headingdirection"))
        self.heading_2.setText(_translate("mappage", "Headingdirection"))
        self.next_maps.setText(_translate("mappage", "Next"))
        self.uhrzeit.setText(_translate("mappage", "TextLabel"))




# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     #Main = QtWidgets.QMainWindow()
#     #ui = Ui_FrontWindow()
#     showMain = Main()
#     sys.exit(app.exec_())
