# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instructionpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from camerapage import Ui_ARWindow, Worker1
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_instructionpage(object):
    def camerapage(self):
        self.ARWindow = QtWidgets.QMainWindow()
        ui = Ui_ARWindow()
        ui.setupUi(self.ARWindow)
        self.ARWindow.show()
        #instructionpage.close()


    def setupUi(self, instructionpage):
        instructionpage.setObjectName("instructionpage")
        instructionpage.resize(1920, 1080)

        self.centralwidget = QtWidgets.QWidget(instructionpage)
        self.centralwidget.setObjectName("centralwidget")

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 60, 1871, 881))
        self.textBrowser.setObjectName("textBrowser")

        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(1450, 992, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setObjectName("back")

        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(1690, 990, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start.setFont(font)
        self.start.setObjectName("start")

        self.start.clicked.connect(self.action)

        self.uhrzeit = QtWidgets.QLabel(self.centralwidget)
        self.uhrzeit.setGeometry(QtCore.QRect(1630, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.uhrzeit.setFont(font)
        self.uhrzeit.setAlignment(QtCore.Qt.AlignCenter)
        self.uhrzeit.setObjectName("uhrzeit")
        instructionpage.setCentralWidget(self.centralwidget)

        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.showTime)
        self.timer.start(1000)

        instructionpage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(instructionpage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        instructionpage.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(instructionpage)
        self.statusbar.setObjectName("statusbar")
        instructionpage.setStatusBar(self.statusbar)

        self.retranslateUi(instructionpage)
        QtCore.QMetaObject.connectSlotsByName(instructionpage)

    def showTime(self):
        current_time = QtCore.QTime.currentTime()
        # converting QTime object to string
        label_time = current_time.toString('hh:mm:ss')
        # showing it to the label
        self.uhrzeit.setText(label_time)

    def action(self):
        self.camerapage()

    def retranslateUi(self, instructionpage):
        _translate = QtCore.QCoreApplication.translate
        instructionpage.setWindowTitle(_translate("instructionpage", "MainWindow"))
        self.textBrowser.setHtml(_translate("instructionpage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-size:16pt; background-color:#ffffff;\">Beim Start Drücken wird die Zeit gestempelt.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:16pt; color:#000000; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque, purus sed sodales vestibulum, ipsum turpis mattis ipsum, vel rhoncus erat sem a libero. Sed pharetra sapien libero, eget convallis est mattis in. Suspendisse non consequat odio. Morbi vehicula condimentum metus. Suspendisse malesuada diam in egestas maximus. Sed et nisi maximus, rhoncus massa vel, dictum ligula. Nullam est diam, tempus non sollicitudin vel, pellentesque in massa. Maecenas tincidunt auctor volutpat. Fusce ornare risus id facilisis pulvinar.</span></p>\n"
"""<br /><p style="text-align:center;"><img src="EDAG_CityBot_300dpi_2.jpg"><br />"""
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:16pt; color:#000000; background-color:#ffffff;\">\nDonec sed sapien ac dolor scelerisque feugiat quis vitae felis. Donec eget ipsum est. Pellentesque dui mauris, cursus porttitor molestie vel, efficitur a lectus. Mauris faucibus, magna eu elementum convallis, ligula nisi sodales turpis, eget aliquam dui augue ut magna. Ut ornare sem elit, ut lacinia libero rhoncus id. Aliquam nec sem tempus, lobortis augue pharetra, imperdiet mauris. Nulla sollicitudin fermentum lacus, non ullamcorper erat porta sed. Curabitur gravida est nec lectus bibendum rhoncus. Integer at iaculis velit, id dictum lectus. Proin id commodo leo, sed tincidunt nibh. Nam gravida sem nec velit scelerisque varius. Phasellus viverra dolor ac enim tincidunt, id auctor diam eleifend. Quisque tincidunt vel mi sit amet bibendum. Nulla vitae augue pretium sem pulvinar molestie. Aenean lobortis id diam a eleifend. In at mollis felis, in eleifend turpis.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Cras egestas metus sed sem pretium consectetur id ut elit. Nam dictum consequat imperdiet. Aenean fringilla mi vitae suscipit finibus. Suspendisse ut justo a purus tincidunt auctor. Vivamus sit amet lorem eu ligula accumsan aliquam non in urna. Vivamus quis ante varius, venenatis risus sit amet, tempor eros. Nunc vestibulum ex vel sagittis tristique. Cras ut felis ultrices, gravida ex quis, hendrerit leo. Ut placerat erat vitae consectetur iaculis.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Donec blandit metus at ipsum tincidunt ultricies. Nunc felis nulla, consectetur nec augue a, auctor eleifend risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque suscipit lectus euismod condimentum mollis. Morbi sit amet cursus magna, sed hendrerit nibh. Cras ultrices augue rhoncus mi tristique pulvinar. Quisque metus risus, eleifend sit amet enim at, pretium ultricies massa. Sed at libero convallis, placerat sapien in, vehicula orci. Etiam aliquam convallis dui accumsan pretium. Donec odio ligula, mattis at ultrices interdum, laoreet semper nibh.</span></p>\n"
"""<br /><p style="text-align:center;"><img src="EDAG_CityBot_300dpi_2.jpg"><br />"""
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:16pt; color:#000000; background-color:#ffffff;\">Nam elementum justo eget tellus cursus faucibus. Nulla porta turpis nibh, quis commodo mi scelerisque sed. Sed eleifend justo vitae orci tincidunt, et pulvinar dolor viverra. Mauris luctus, ante in fringilla ultricies, dui ipsum elementum augue, a vestibulum orci sapien vestibulum ex. Aenean id consectetur magna. Fusce et accumsan neque. In hendrerit urna ut turpis ullamcorper finibus eu eget arcu. Morbi dignissim vestibulum erat, id malesuada enim vulputate eu. In quis nisi vitae dui aliquam elementum. Sed aliquet mauris ac porta lobortis. Pellentesque non ante tincidunt, faucibus urna vel, feugiat neque. Nullam id turpis neque. Sed diam turpis, commodo nec rutrum at, lobortis et nisl. In accumsan sodales magna nec pellentesque.</span></p></body></html>"))
        self.back.setText(_translate("instructionpage", "Back"))
        self.start.setText(_translate("instructionpage", "Start"))
        self.uhrzeit.setText(_translate("instructionpage", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    instructionpage = QtWidgets.QMainWindow()
    ui = Ui_instructionpage()
    ui.setupUi(instructionpage)
    instructionpage.show()
    sys.exit(app.exec_())
