# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mappage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import io
import folium
from instructionpage import Ui_instructionpage

from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_mappage(object):
    def instructionpage(self):
        self.instructionpage = QtWidgets.QMainWindow()
        ui = Ui_instructionpage()
        ui.setupUi(self.instructionpage)
        self.instructionpage.show()
        #self.mappage.close()


    def setupUi(self, mappage):
        mappage.setObjectName("mappage")
        mappage.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(mappage)
        self.centralwidget.setObjectName("centralwidget")

        self.maps = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.maps.setGeometry(QtCore.QRect(10, 20, 1181, 1001))
        self.maps.setObjectName("maps")

        coordinate1 = (48.274691, 11.561639)
        m = folium.Map(
            tiles='OpenStreetMap',
            zoom_start=18,
            location=coordinate1
        )
        startpos = [48.2747192, 11.5613712]

        folium.Marker(startpos, popup='Start Position').add_to(m)

        folium.Circle(
            radius=100,
            location=[49.85535748057516, 7.60608913278368],
            color="crimson",
            fill=True,
        ).add_to(m)

        # save map data to data object
        data = io.BytesIO()
        m.save(data, close_file=False)
        self.maps.setHtml(data.getvalue().decode())

        self.startlat = QtWidgets.QLabel(self.centralwidget)
        self.startlat.setGeometry(QtCore.QRect(1400, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startlat.setFont(font)
        self.startlat.setMouseTracking(False)
        self.startlat.setObjectName("startlat")

        self.startlong = QtWidgets.QLabel(self.centralwidget)
        self.startlong.setGeometry(QtCore.QRect(1400, 120, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startlong.setFont(font)
        self.startlong.setObjectName("startlong")

        self.endlat = QtWidgets.QLabel(self.centralwidget)
        self.endlat.setGeometry(QtCore.QRect(1400, 290, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endlat.setFont(font)
        self.endlat.setMouseTracking(False)
        self.endlat.setObjectName("endlat")

        self.endlong = QtWidgets.QLabel(self.centralwidget)
        self.endlong.setGeometry(QtCore.QRect(1400, 330, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endlong.setFont(font)
        self.endlong.setMouseTracking(False)
        self.endlong.setObjectName("endlong")

        self.startlat_2 = QtWidgets.QLabel(self.centralwidget)
        self.startlat_2.setGeometry(QtCore.QRect(1590, 80, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startlat_2.setFont(font)
        self.startlat_2.setMouseTracking(False)
        self.startlat_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.startlat_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.startlat_2.setObjectName("startlat_2")

        self.startlong_2 = QtWidgets.QLabel(self.centralwidget)
        self.startlong_2.setGeometry(QtCore.QRect(1590, 120, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startlong_2.setFont(font)
        self.startlong_2.setMouseTracking(False)
        self.startlong_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.startlong_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.startlong_2.setLineWidth(1)
        self.startlong_2.setTextFormat(QtCore.Qt.AutoText)
        self.startlong_2.setWordWrap(False)
        self.startlong_2.setObjectName("startlong_2")

        self.endlat_2 = QtWidgets.QLabel(self.centralwidget)
        self.endlat_2.setGeometry(QtCore.QRect(1590, 290, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endlat_2.setFont(font)
        self.endlat_2.setMouseTracking(False)
        self.endlat_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.endlat_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.endlat_2.setObjectName("endlat_2")

        self.endlong_2 = QtWidgets.QLabel(self.centralwidget)
        self.endlong_2.setGeometry(QtCore.QRect(1590, 330, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endlong_2.setFont(font)
        self.endlong_2.setMouseTracking(False)
        self.endlong_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.endlong_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.endlong_2.setObjectName("endlong_2")

        self.uhrzeit = QtWidgets.QLabel(self.centralwidget)
        self.uhrzeit.setGeometry(QtCore.QRect(1630, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.uhrzeit.setFont(font)
        self.uhrzeit.setAlignment(QtCore.Qt.AlignCenter)
        self.uhrzeit.setObjectName("uhrzeit")
        mappage.setCentralWidget(self.centralwidget)

        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.showTime)
        self.timer.start(1000)

        self.startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(1690, 160, 171, 28))
        self.startbutton.setObjectName("startbutton")

        self.endbutton = QtWidgets.QPushButton(self.centralwidget)
        self.endbutton.setGeometry(QtCore.QRect(1690, 370, 171, 28))
        self.endbutton.setObjectName("endbutton")

        self.distance = QtWidgets.QLabel(self.centralwidget)
        self.distance.setGeometry(QtCore.QRect(1280, 480, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.distance.setFont(font)
        self.distance.setMouseTracking(False)
        self.distance.setObjectName("distance")

        self.distance_2 = QtWidgets.QLabel(self.centralwidget)
        self.distance_2.setGeometry(QtCore.QRect(1590, 480, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.distance_2.setFont(font)
        self.distance_2.setMouseTracking(False)
        self.distance_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.distance_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.distance_2.setObjectName("distance_2")
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setGeometry(QtCore.QRect(1370, 520, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.heading.setFont(font)
        self.heading.setMouseTracking(False)
        self.heading.setObjectName("heading")

        self.heading_2 = QtWidgets.QLabel(self.centralwidget)
        self.heading_2.setGeometry(QtCore.QRect(1590, 520, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.heading_2.setFont(font)
        self.heading_2.setMouseTracking(False)
        self.heading_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.heading_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.heading_2.setObjectName("heading_2")

        self.maps_coor_table = QtWidgets.QTableWidget(self.centralwidget)
        self.maps_coor_table.setGeometry(QtCore.QRect(1280, 590, 581, 321))
        self.maps_coor_table.setObjectName("maps_coor_table")
        self.maps_coor_table.setColumnCount(0)
        self.maps_coor_table.setRowCount(0)

        self.next_maps = QtWidgets.QPushButton(self.centralwidget)
        self.next_maps.setGeometry(QtCore.QRect(1690, 990, 171, 28))
        self.next_maps.setObjectName("next_maps")
        mappage.setCentralWidget(self.centralwidget)

        def action(self):
            self.instructionpage()

        self.next_maps.clicked.connect(lambda: action(self))

        self.menubar = QtWidgets.QMenuBar(mappage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        mappage.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(mappage)
        self.statusbar.setObjectName("statusbar")
        mappage.setStatusBar(self.statusbar)

        self.retranslateUi(mappage)
        QtCore.QMetaObject.connectSlotsByName(mappage)

    def showTime(self):
        current_time = QtCore.QTime.currentTime()
        # converting QTime object to string
        label_time = current_time.toString('hh:mm:ss')
        # showing it to the label
        self.uhrzeit.setText(label_time)

    def retranslateUi(self, mappage):
        _translate = QtCore.QCoreApplication.translate
        mappage.setWindowTitle(_translate("mappage", "MainWindow"))
        self.startlat.setText(_translate("mappage", "Start Latitude"))
        self.startlong.setText(_translate("mappage", "Start Longitude"))
        self.endlat.setText(_translate("mappage", "End Latitude"))
        self.endlong.setText(_translate("mappage", "End Longitude"))
        self.startlat_2.setText(_translate("mappage", "Start Latitude"))
        self.startlong_2.setText(_translate("mappage", "Start Longitude"))
        self.endlat_2.setText(_translate("mappage", "End Latitude"))
        self.endlong_2.setText(_translate("mappage", "End Latitude"))
        self.startbutton.setText(_translate("mappage", "Set as Startposition"))
        self.endbutton.setText(_translate("mappage", "Set as Endposition"))
        self.distance.setText(_translate("mappage", "Distance from start to end"))
        self.distance_2.setText(_translate("mappage", "Distance"))
        self.heading.setText(_translate("mappage", "Headingdirection"))
        self.heading_2.setText(_translate("mappage", "Headingdirection"))
        self.next_maps.setText(_translate("mappage", "Next"))
        self.uhrzeit.setText(_translate("mappage", "TextLabel"))


from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    #instructionpage = QtWidgets.QMainWindow()
    mappage = QtWidgets.QMainWindow()
    ui = Ui_mappage()
    ui.setupUi(mappage)
    mappage.show()
    sys.exit(app.exec_())
